#!/usr/bin/env python3

import asyncio
import websockets
import json


async def get_data():
    with open("quicksort/results.txt") as f:
        return json.load(f)


async def response(ws, path):
    data = await get_data()
    while True:
        last_data = await get_data()
        if last_data != data:
            data = last_data
            await ws.send(json.dumps(data))
        await asyncio.sleep(1)

start_server = websockets.serve(response, "localhost", 5000)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
