#!/usr/bin/env python3

import argparse
import collections
import os
import operator
import itertools
import subprocess
import time
import re
import json
import typing


DATA_FP = os.path.join(os.path.dirname(__file__), "data")
INPUT_FP = os.path.join(DATA_FP, "input.txt")
ANSWER_FP = os.path.join(DATA_FP, "answer.txt")
OUTPUT_FP = os.path.join(DATA_FP, "output.txt")
RESULTS_FP = os.path.join(DATA_FP, "results.txt")
TIMEOUT = 60
LANGS = ("cpp", "jl", "ocaml", "py")
RE_INFO = re.compile(r"run_([a-z0-9]*)")
PARSER = argparse.ArgumentParser()
PARSER.add_argument("files", nargs="*")


Runnable = collections.namedtuple("Runnable", ["name", "lang", "cmd_args"])


def to_cmd_args(fp, lang):
    if lang == "py":
        return ["python3", fp]
    elif lang == "jl":
        return ["julia", fp]
    else:
        return [fp]


def to_runnable(fp):
    fn = os.path.basename(fp)
    match = RE_INFO.match(fn)
    if match:
        lang = match.group(1)
        if lang in LANGS:
            return Runnable(fn, lang, to_cmd_args(fp, lang))
    return None


def check_output(fpo=OUTPUT_FP, fpa=ANSWER_FP):
    if not os.path.exists(fpa):
        raise FileNotFoundError("No answer file")
    if not os.path.exists(fpo):
        raise FileNotFoundError("No output file")
    with open(fpa) as fa, open(fpo) as fo:
        for out, ans in itertools.zip_longest(fo, fa, fillvalue=None):
            if out is None or ans is None:
                return False
            if out.strip() != ans.strip():
                return False
    return True


def clean_output(fp=OUTPUT_FP):
    try:
        if os.path.exists(fp):
            print("deleting output file")
            os.remove(fp)
        else:
            print("no ouput file to delete")
    except Exception as e:
        print(f"deletion failed: {e}")


def main(args) -> typing.Iterator:
    """For each runnable found, time it, store and yield result. Previous
    stored results are deleted if a runnable is found.
    """
    if not os.path.exists(DATA_FP):
        os.makedirs(DATA_FP)
    folder_path = os.path.dirname(os.path.abspath(__file__))
    fps = [os.path.join(folder_path, fn) for fn in args.files]
    if not fps:
        fps = sorted(e.path for e in os.scandir(folder_path))

    results = {}

    for runnable in filter(lambda r: r is not None,
                    map(to_runnable, fps)):
        print(f"running {runnable.name}")
        yield runnable.name, "running"
        try:
            start = time.perf_counter()

            paths = f"{os.path.abspath(INPUT_FP)}\n{os.path.abspath(OUTPUT_FP)}"
            subprocess.run(runnable.cmd_args,
                           cwd=folder_path,
                           input=paths,
                           text=True,
                           timeout=TIMEOUT)

            t = time.perf_counter() - start
            print(f"time: {t:.2f}s")

            is_correct = check_output()
            print("answer is correct" if is_correct
                  else "/!\\ answer is wrong /!\\")

            results[runnable.name] = t if is_correct else "WA"
        except subprocess.TimeoutExpired:
            print(f"Execution failed: Time limit exceeded")
            results[runnable.name] = "TLE"
        except Exception as e:
            print(f"Execution failed: {e}")
            results[runnable.name] = "failed"
        finally:
            clean_output()
            print()
            with open(RESULTS_FP, "w") as f:
                json.dump(results, f, indent=2)

            yield runnable.name, results[runnable.name]


if __name__ == "__main__":
    args = PARSER.parse_args()

    for _ in main(args):
        pass
