#!/usr/bin/env python3

import argparse
import collections
import os
import operator
import subprocess
import time
import re
import json
import typing


ANSWER_FP = os.path.join(os.path.dirname(__file__), "answer.txt")
RESULTS_FP = os.path.join(os.path.dirname(__file__), "results.txt")
LANGS = ("cpp", "jl", "ocaml", "py")
RE_INFO = re.compile(r"run_([a-z0-9]*)")
PARSER = argparse.ArgumentParser()
PARSER.add_argument("files", nargs="*")


Runnable = collections.namedtuple("Runnable", ["name", "lang", "cmd_args"])


def to_cmd_args(fp, lang):
    if lang == "py":
        return ["python3", fp]
    elif lang == "jl":
        return ["julia", fp]
    else:
        return [fp]


def to_runnable(fp):
    fn = os.path.basename(fp)
    match = RE_INFO.match(fn)
    if match:
        lang = match.group(1)
        if lang in LANGS:
            return Runnable(fn, lang, to_cmd_args(fp, lang))
    return None


def check_answer(file_path):
    if not os.path.exists(file_path):
        raise FileNotFoundError("No answer file")
    with open(file_path) as f:
        for line, sol in zip(f, range(1000000)):
            if int(line) != sol:
                return False
    return True


def clean_answer(file_path):
    try:
        if os.path.exists(file_path):
            print("deleting answer file")
            os.remove(file_path)
        else:
            print("no answer file to delete")
    except Exception as e:
        print(f"deletion failed: {e}")


def main(args) -> typing.Iterator:
    """For each runnable found, time it, store and yield result. Previous
    stored results are deleted if a runnable is found.
    """
    folder_path = os.path.dirname(os.path.abspath(__file__))
    fps = [os.path.join(folder_path, fn) for fn in args.files]
    if not fps:
        fps = sorted(e.path for e in os.scandir(folder_path))

    results = {}

    for runnable in filter(lambda r: r is not None,
                    map(to_runnable, fps)):
        print(f"running {runnable.name}")
        yield runnable.name, "running"
        try:
            start = time.perf_counter()
            subprocess.run(runnable.cmd_args, cwd=folder_path)
            t = time.perf_counter() - start
            print(f"time: {t:.2f}s")

            is_correct = check_answer(ANSWER_FP)
            print("answer is correct" if is_correct
                  else "/!\\ answer is wrong /!\\")

            results[runnable.name] = t if is_correct else "WA"
        except Exception as e:
            print(f"Execution failed: {e}")
            results[runnable.name] = "failed"
        finally:
            clean_answer(ANSWER_FP)
            print()
            with open(RESULTS_FP, "w") as f:
                json.dump(results, f, indent=2)

            yield runnable.name, results[runnable.name]


if __name__ == "__main__":
    args = PARSER.parse_args()

    for _ in main(args):
        pass
