#!/usr/bin/env python3

import random
import tqdm
import argparse
import os

DATA_FP = os.path.join(os.path.dirname(__file__), "data")
INPUT_FP = os.path.join(DATA_FP, "input.txt")
ANSWER_FP = os.path.join(DATA_FP, "answer.txt")

ARGUMENTS = {
    "size": {"nargs": "?", "default": 1000, "type": int}
}

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    for name, kwargs in ARGUMENTS.items():
        parser.add_argument(name, **kwargs)
    args = parser.parse_args()

    numbers = list(range(args.size))
    with open(ANSWER_FP, "w") as f:
        for n in tqdm.tqdm(numbers):
            f.write(f"{n}\n")
    print(f"wrote {ANSWER_FP}, with {args.size} elements")

    random.shuffle(numbers)
    with open(INPUT_FP, "w") as f:
        for n in tqdm.tqdm(numbers):
            f.write(f"{n}\n")
    print(f"wrote {INPUT_FP}, with {args.size} elements")
